### ISSUE TITLE
PHP 8.3.4

### ISSUE THREAD

**Issue by KupueIIIKo** [jhanley-com/php-ssh2-windows#4]
Out - 8.3.4, but I failed to collect!!! Instruction

**Comment by KupueIIIKo** [comment]
C:\Windows\System32
$ cd C:\php-dev\php-8.3.4RC1-src

C:\php-dev\php-8.3.4RC1-src
$ phpsdk_deps --update --branch master

Fatal error: Uncaught SDK\Exception: Failed to fetch supported branches in C:\php-dev\php-sdk-binary-tools-master\lib\php\libsdk\SDK\Config.php:172
Stack trace:
#0 C:\php-dev\php-sdk-binary-tools-master\lib\php\libsdk\SDK\Config.php(182): SDK\Config::getKnownBranches()
#1 C:\php-dev\php-sdk-binary-tools-master\bin\phpsdk_deps.php(105): SDK\Config::setCurrentBranchName('master')
#2 {main}
  thrown in C:\php-dev\php-sdk-binary-tools-master\lib\php\libsdk\SDK\Config.php on line 172

**Comment by KupueIIIKo** [comment]
The problem was winsdk) Reinstalled it seemed to go
